# Proxy server listening address
listen_addr: ":8080"

# Load balancer type (round_robin, least_connections)
balancer_type: "round_robin"

# Backend server list
servers:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"

# Health check configuration
health_check:
  interval: 10s  # Check interval
  timeout: 2s    # Timeout duration

# Log level (debug, info, warn, error, fatal)
log_level: "info"
