# Proxy server listening address
listen_addr: ":8080"

# Load balancer type (round_robin, least_connections, weighted_round_robin)
balancer_type: "weighted_round_robin"

# Backend server list
servers:
  - address: "http://localhost:8081"
    weight: 3
  - address: "http://localhost:8082"
    weight: 2
  - address: "http://localhost:8083"
    weight: 1

# Health check configuration
health_check:
  interval: 10s  # Check interval
  timeout: 2s    # Timeout duration

# Log level (debug, info, warn, error, fatal)
log_level: "info"
