# 代理服务器监听地址
listen_addr: ":8080"

# 负载均衡器类型 (round_robin, least_connections)
balancer_type: "round_robin"

# 后端服务器列表
servers:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"

# 健康检查配置
health_check:
  interval: 10s  # 检查间隔
  timeout: 2s    # 超时时间

# 日志级别 (debug, info, warn, error, fatal)
log_level: "info"
